### ISSUE TITLE
Add blog feeds feature

### ISSUE THREAD

**Issue by pepoospina** [uprtcl/linked-thoughts#27]
Add the way to store `linksTo` edges to perspectives, similar to children edges. This is the work of [issue 38 on the server](https://github.com/uprtcl/js-uprtcl-server/issues/38). Once the links are there, we will be able to filter queries based on them.

Then modify the frontend application with the help of Pepo. The idea is that, when a blog is added to the blog section, it is updated to include a `linkTo` edge that links to the "concept of blog" perspective (that needs to be created as part of the application elements preapration).

Once this is done, add an endpoint on the backend to explore all elements that linksTo the  "concept of blog" perspective and return them as the blog feed. This is [issue 37](https://github.com/uprtcl/js-uprtcl-server/issues/37) on the serve

**Comment by pepoospina** [comment]
@milieuChris I will create a branch of linked thoughts repo where I prepare the frontend work

**Comment by milieuChris** [comment]
Note: This is the “lighthouse” node for the blog concept mentioned in Discord.
